### PR TITLE
Add NumPy v2 compatibility

### PR DESCRIPTION
**Pull request by violuke**
Fixes:

```
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.. Did you mean: 'float16'?
```

and

```
AttributeError: `np.string_` was removed in the NumPy 2.0 release. Use `np.bytes_` instead.. Did you mean: 'strings'?
```

When used with NumPy v2+.

https://numpy.org/devdocs/release/2.0.0-notes.html#numpy-2-0-python-api-removals

### CODE REVIEW

**Comment by LucaCappelletti94** [comment]
They did a number with the new Numpy release, retro-compatibility-wise - thank you for the pull request. I will take a look into it shortly.

**Comment by LucaCappelletti94** [comment]
Could you kindly also add just a couple tests for this new corner case in the test suite?

**Comment by violuke** [comment]
Thanks for the quick review. I'd be happy to, but I'm not quite sure how best to test this over two NumPy versions. I've never had to do this before. Do you have any suggestions?

**Comment by LucaCappelletti94** [comment]
I will add two different test suites modalities.

**Comment by violuke** [comment]
Thank you, this is very much appreciated!

**Pull request merged**
